// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employment struct {
	ID           string        `json:"id"`
	Member       *Member       `json:"member"`
	Organization *Organization `json:"organization"`
}

type EmploymentInput struct {
	MemberID       string `json:"memberId"`
	OrganizationID string `json:"organizationId"`
}

type Member struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type MemberInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"LastName"`
}

type Mutation struct {
}

type Organization struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type OrganizationInput struct {
	Name string `json:"name"`
}

type Query struct {
}
